#!/usr/bin/env node
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

export const FLUENT_ICON_NAMES = [
  'settings', 'brain', 'database', 'apps', 'store_microsoft', 'alert',
  'wallet', 'money', 'receipt_money', 'document_pdf', 'document_text',
  'document_mention', 'folder', 'folder_open', 'archive', 'bookmark',
  'arrow_import', 'arrow_export', 'arrow_download', 'arrow_upload',
  'shield', 'shield_lock', 'key', 'lock_closed', 'eye', 'image',
  'search', 'globe', 'code', 'plug_connected', 'toolbox', 'wrench',
  'sparkle', 'paint_brush', 'color', 'grid', 'panel_left', 'panel_right',
  'panel_right_gallery', 'chart_multiple', 'history', 'calendar', 'chat',
  'people', 'person', 'home', 'info', 'warning', 'cloud', 'window_apps',
]

const unsafe = /<script|<image|<style|\son\w+\s*=|https?:|url\s*\(|#[0-9a-f]{3,8}/i

export function normalizeSvg(source, name) {
  let svg = source.trim()
  if (!svg.startsWith('<svg ') || !svg.endsWith('</svg>')) throw new Error(`${name}: not an svg`)
  if (!svg.includes('viewBox="0 0 16 16"')) throw new Error(`${name}: not a 16px icon`)
  const withoutNamespace = svg.replace(/\sxmlns="http:\/\/www\.w3\.org\/2000\/svg"/, '')
  if (unsafe.test(withoutNamespace)) throw new Error(`${name}: unsafe or non-monochrome svg`)
  svg = svg.replace(/\s(?:width|height)="16"/g, '')
  svg = svg.replace('<svg ', '<svg fill="currentColor" ')
  return svg
}

export function generate({ root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..') } = {}) {
  const iconDir = path.join(root, 'node_modules', '@fluentui', 'svg-icons', 'icons')
  const output = path.join(root, 'src', 'client', 'generated', 'fluent-icons.ts')
  const rows = FLUENT_ICON_NAMES.map((name) => {
    const source = fs.readFileSync(path.join(iconDir, `${name}_16_regular.svg`), 'utf8')
    return `  ${JSON.stringify(name)}: ${JSON.stringify(normalizeSvg(source, name))},`
  })
  const code = [
    '/** Generated by scripts/generate-icons.mjs from Fluent UI System Icons 16 Regular. */',
    'export const GENERATED_FLUENT_ICONS = {',
    ...rows,
    '} as const',
    '',
    'export type FluentIconName = keyof typeof GENERATED_FLUENT_ICONS',
    '',
  ].join('\n')
  fs.mkdirSync(path.dirname(output), { recursive: true })
  fs.writeFileSync(output, code)
  return code
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  generate()
  console.log(`generated ${FLUENT_ICON_NAMES.length} Fluent icons`)
}
